# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lgcodegen2',
                'doc_host': 'https://jojohannsen.github.io',
                'git_url': 'https://github.com/jojohannsen/lgcodegen2',
                'lib_path': 'lgcodegen2'},
  'syms': {'lgcodegen2.core': {'lgcodegen2.core.foo': ('core.html#foo', 'lgcodegen2/core.py')}}}
