"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['get_graph_data']

# %% ../nbs/00_core.ipynb 3
from fastcore.foundation import L
from fastcore.utils import *

# %% ../nbs/00_core.ipynb 8
def _get_pairs(graph_notation: str):
    """Given a text representation of the graph, return unprocessed pairs direct from the notation"""
    pairs = []
    for line in graph_notation.splitlines():
        line_components = [v.strip() for v in line.split("->")]
        line_pairs = list(zip(line_components, line_components[1:]))
        pairs.extend(line_pairs)
    return pairs

def _expand_commas(graph_pairs):
    for l,r in graph_pairs:
        if "," in l and "(" not in l: llist = [x.strip() for x in l.split(",")]
        else: llist = [l]
        if "," in r and "(" not in r: rlist = [x.strip() for x in r.split(",")]
        else: rlist = [r]
        for left in llist:
            for right in rlist:
                yield left, right

def _expand_node_lists(graph_pairs):
    return list(_expand_commas(graph_pairs))

def get_graph_data(graph_notation: str):
    """Given a text representation of the graph, return pairs of components"""
    pairs = _get_pairs(graph_notation)
    pairs = _expand_node_lists(pairs)
    return pairs
